# NumPy

In [1]:
import numpy as np #importing numpy lib

In [2]:
arr1 = np.array([[1,2,3,4], [5,9,8,7],[7,5,1,3]]) # creating the ndim array
arr1

array([[1, 2, 3, 4],
       [5, 9, 8, 7],
       [7, 5, 1, 3]])

In [3]:
print(np.size(arr1)) # printing the size of the array

12


In [4]:
print(arr1.ndim) # printitng the dimentions of the array

2


In [5]:
print(arr1.shape) # printing the dimentions

(3, 4)


In [6]:
print(arr1.data) # memory location of the array

# Statistical Function:

In [7]:
arr = np.array([[1,2,3,4], [5,9,8,7],[7,5,1,3]]) # creating the ndim array
arr

array([[1, 2, 3, 4],
       [5, 9, 8, 7],
       [7, 5, 1, 3]])

In [8]:
arr.dtype  # data type of the aray

dtype('int32')

In [9]:
arr.itemsize # item size of the array

4

In [10]:
arr.shape # shape of the array

(3, 4)

In [11]:
arr.size # total number of the elements present in the array

12

In [12]:
# changing the datatype of the array:
arr = np.array([[1,2,3,4], [5,9,8,7],[7,5,1,3]], dtype = np.float64) # creating the ndim array with float64 byte data
arr

array([[1., 2., 3., 4.],
       [5., 9., 8., 7.],
       [7., 5., 1., 3.]])

In [13]:
# creating the complax array:
arr = np.array([[1,2,3,4], [5,9,8,7],[7,5,1,3]], dtype = np.complex64) # creating the ndim array
arr

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 9.+0.j, 8.+0.j, 7.+0.j],
       [7.+0.j, 5.+0.j, 1.+0.j, 3.+0.j]], dtype=complex64)

In [14]:
arr = np.array([[1,2,3,4], [5,9,8,7],[7,5,1,3]], dtype = np.complex128) # creating the ndim array
arr

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [5.+0.j, 9.+0.j, 8.+0.j, 7.+0.j],
       [7.+0.j, 5.+0.j, 1.+0.j, 3.+0.j]])

In [15]:
# sum of the elements present in the array
b = np.array([[1,2,3,4], [5,9,8,7],[7,5,1,3]])
np.sum(b)

55

In [16]:
# axis vise sum:
print(np.sum(b, axis = 0)) # columns
print(np.sum(b, axis = 1)) # rows

[13 16 12 14]
[10 29 16]


In [17]:
# minimum value:
print(b)
np.amin(b)

[[1 2 3 4]
 [5 9 8 7]
 [7 5 1 3]]


1

In [18]:
print(np.amin(b, axis = 0)) # minimum of each column
print(np.amin(b, axis = 1)) # minimum of each row

[1 2 1 3]
[1 5 1]


In [19]:
#maximum value:
print(np.amax(b)) # overall max value of the ndArray

9


In [20]:
print(np.amax(b, axis = 0))# maximum of each column
print(np.amax(b, axis = 1)) # maximum of each row

[7 9 8 7]
[4 9 7]


In [21]:
# Mean:

print(np.mean(b)) # printing the mean of the nd array:

4.583333333333333


In [22]:
print(np.mean(b, axis = 0)) # along the column
print(np.mean(b, axis = 1)) # along the Row

[4.33333333 5.33333333 4.         4.66666667]
[2.5  7.25 4.  ]


In [23]:
# Median:

print(np.median(b)) # printing the median of the axis:

4.5


In [24]:
print(np.median(b, axis = 0)) # along the column
print(np.median(b, axis = 1)) # along the Row

[5. 5. 3. 4.]
[2.5 7.5 4. ]


In [25]:
# Standard Daviation:

print(np.std(b)) # overall standared daviation of the array:

2.5967394084804805


In [26]:
print(np.std(b, axis = 0)) # along the column
print(np.std(b, axis = 1)) # along the Row

[2.49443826 2.86744176 2.94392029 1.69967317]
[1.11803399 1.47901995 2.23606798]


In [27]:
var = np.std(b) # variance 
print(var**2)

6.743055555555555


In [28]:
# Variance:

print(np.var(b)) # overall variance:


6.743055555555556


In [29]:
print(np.var(b, axis = 0)) # along the column
print(np.var(b, axis = 1)) # along the Row

[6.22222222 8.22222222 8.66666667 2.88888889]
[1.25   2.1875 5.    ]


In [30]:
# normal average:
b1 = np.array([5,9,7,2,6,4,3,5,4])
print(np.average(b1)) # overall normal average:

5.0


In [31]:
# average with weights:

w = np.array([0.25, 0.16, 0.14, 0.5, 0.7, 0.2, 0.1, 0.4, 0.26])
print(w)

[0.25 0.16 0.14 0.5  0.7  0.2  0.1  0.4  0.26]


In [32]:
print(np.average(b1, weights = w))

4.800738007380073


In [33]:
# percentile:
print(b1) # printing the array
print(np.percentile(b1, 5, 0))
print(np.percentile(b1, 2, 0))
print(np.percentile(b1, 6, 0))

[5 9 7 2 6 4 3 5 4]
2.4
2.16
2.48


In [34]:
# peak to peek = Maxvalue - minvalue:

print(b)

[[1 2 3 4]
 [5 9 8 7]
 [7 5 1 3]]


In [35]:
print(b1)

[5 9 7 2 6 4 3 5 4]


In [36]:
print(np.ptp(b1, 0))
print(np.ptp(b, 1))
print(np.ptp(b, 0))
print(np.ptp(b1, 0))




7
[3 4 6]
[6 7 7 4]
7


In [37]:

# rashape:

x = np.array([[1,2,3], [5,6, 7]])
print(x)


[[1 2 3]
 [5 6 7]]


# Slicing:

In [38]:
# 2D array:

e = np.array([[23,25,27,29], [43,45,47,49], [62,66,68,70]])
print(e)

[[23 25 27 29]
 [43 45 47 49]
 [62 66 68 70]]


In [39]:
print(e, "\n")

[[23 25 27 29]
 [43 45 47 49]
 [62 66 68 70]] 



In [40]:
print(e[1:3]) # Print 1th row to 2th row

[[43 45 47 49]
 [62 66 68 70]]


In [41]:
print(e[0, 3]) # print 0th row and 3rd value

29


In [42]:
print(e[2,3]) # printing in 2th 3rd value

70


In [43]:
print(e[0:2, 1]) # from 0th row to the 1st row on the 1st column values

[25 45]


In [44]:
print(e[-1]) # printing the -1th index

[62 66 68 70]


In [45]:
 print(e[-1, 0:2]) # in -1th row oth column to the 1th column values

[62 66]


#  Stacking

In [46]:
h1 = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
h2 = np.array([[12,13,14,15],[16,17,18,19],[20,21,22,23]])
print(h1, "\n\n\n", h2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 


 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [47]:
# Horizontal Stacking:

print(np.hstack((h1, h2)), "\n\n\n") # here h1 rows are stacked on the h2's rows 
print(np.hstack((h2, h1))) # # here h2 columns are stacked on the h1's column 

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]] 



[[12 13 14 15  0  1  2  3]
 [16 17 18 19  4  5  6  7]
 [20 21 22 23  8  9 10 11]]


In [48]:
# Vertical Stacking:

print(np.vstack((h1, h2)), "\n\n\n")  # here h1 columns are stacked on the h2's column 
print(np.vstack((h2, h1))) # here h2 columns are stacked on the h1's column 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 



[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# Random Number generator:

In [49]:
from numpy import random

# print integer random nomber
a = random.randint(100)
a

54

In [52]:
# print float random nomber
a1 = random.rand()
print(a1)

0.1950548244556054


In [53]:
x1 = random.rand(100) # 0 to 100 random numbers
print(x1)

[0.18301335 0.51460946 0.22830861 0.89498978 0.05774455 0.20588501
 0.73726353 0.79542095 0.92335053 0.34197371 0.26483849 0.96827533
 0.51549299 0.69205933 0.7939604  0.10394948 0.77115532 0.69473743
 0.15683207 0.97651862 0.11434532 0.87429268 0.59029719 0.21335095
 0.91152711 0.14046113 0.32573913 0.3400446  0.93663452 0.43775671
 0.729039   0.94167916 0.61331634 0.62447129 0.58689385 0.75731649
 0.4963074  0.51445615 0.25762855 0.931703   0.95801041 0.43197836
 0.66765478 0.30259091 0.26953189 0.12979347 0.37691462 0.0668516
 0.16563902 0.99418183 0.09725655 0.26195753 0.75289086 0.32172857
 0.09299772 0.02244208 0.85789596 0.92374935 0.2985085  0.49442168
 0.40530805 0.10561144 0.72828248 0.8103402  0.12088192 0.51064594
 0.65279467 0.77745999 0.12287318 0.18135452 0.52148702 0.3848716
 0.89541334 0.52562196 0.21891732 0.54801631 0.79408547 0.90474637
 0.91583218 0.73872023 0.54580254 0.04358659 0.92600144 0.83585433
 0.40871237 0.06188984 0.08965664 0.40336898 0.18537363 0.991780

# Matrix in NumPy:

In [ ]:
# to create the matrix in array:


# Percentile & Interquartile in NumPy: